import { layout } from './layout.mjs';
import { esc, attr, csrf, notice, nextNumber } from './ui-helpers.mjs';

const step = (n, title, current) => `<div class="step ${n === current ? 'current' : n < current ? 'done' : ''}"><span>${n}</span>${esc(title)}</div>`;

function julesConnectionStep({ error, csrfToken }) {
  return `<div class="eyebrow">Step 01 / 03</div><h1>Connect Jules</h1><p class="lead">Paste your Jules API key. Research Facility will discover the repositories it can access.</p>${notice(error)}<form method="post" action="/setup/jules" class="form-card">${csrf(csrfToken)}<label for="julesKey">Jules API key</label><input id="julesKey" name="julesKey" type="password" required autocomplete="off" placeholder="Paste API key"><div class="form-actions"><button class="primary">Test Jules connection</button><a href="https://jules.google.com/settings" target="_blank" rel="noopener">Get an API key ↗</a></div></form><p class="help">The key is sent only to this local server and is never shown again.</p>`;
}

function repositoryConnectionStep({ sources = [], binding, error, branches = [], csrfToken, prefill = {}, rebind = false, connectedJules = false }) {
  const options = sources.map(source => `<label class="repo-option"><input type="radio" name="sourceName" value="${attr(source.name)}" ${sameSource(source, prefill) ? 'checked' : ''}><span><strong>${esc(source.githubRepo.owner)}/${esc(source.githubRepo.repo)}</strong><small>${esc(source.githubRepo.defaultBranch?.displayName ?? 'GitHub repository')}</small></span></label>`).join('');
  return `<div class="eyebrow">Step 02 / 03</div><h1>Choose the destination</h1><p class="lead">Select the repository Jules should work on, then verify GitHub access and the base branch.</p>${notice(error)}${error?.startsWith('Could not locate') ? '<div class="diagnostic"><strong>Check these common causes</strong><ul><li>Jules has not been granted access to this repository.</li><li>The GitHub account connected to Jules cannot see it.</li><li>The repository has not been added as a Jules source.</li></ul><a href="/setup/guide">Show setup instructions →</a></div>' : ''}${connectedJules ? notice(`Jules connected · ${sources.length} repositories available`, 'success') : ''}<form method="post" action="/setup/repository" class="form-card">${csrf(csrfToken)}${rebind ? '<input type="hidden" name="rebind" value="1">' : ''}${options ? `<fieldset><legend>Repositories available to Jules</legend><div class="repo-list">${options}<label class="repo-option"><input type="radio" name="sourceName" value="__manual__"><span><strong>Enter a repository manually</strong><small>Research Facility will locate it in Jules</small></span></label></div></fieldset>` : `<div class="empty">No Jules repositories are currently available. Connect the repository in Jules, then retry discovery.</div>`}<details class="fallback" ${!options ? 'open' : ''}><summary>GitHub owner and repository</summary><div class="field-grid"><div><label for="owner">GitHub owner</label><input id="owner" name="owner" value="${attr(prefill.owner ?? '')}" placeholder="example-owner"></div><div><label for="repo">Repository</label><input id="repo" name="repo" value="${attr(prefill.repo ?? '')}" placeholder="example-research-repo"></div></div><p class="help">Research Facility still resolves the Jules source from the official API. Select “Enter a repository manually” above when using these fields.</p></details><div class="field-grid"><div><label for="branch">Base branch</label><input id="branch" name="branch" value="${attr(prefill.branch ?? 'main')}" required></div><div><label for="githubToken">GitHub token</label><input id="githubToken" name="githubToken" type="password" autocomplete="off" placeholder="${binding ? 'Leave blank to keep current token' : 'Fine-grained token'}" ${binding ? '' : 'required'}></div></div>${branches.length ? `<div class="branch-choices"><strong>Available branches</strong>${branches.map(name => `<label><input type="radio" name="branchChoice" value="${attr(name)}">${esc(name)}</label>`).join('')}</div>` : ''}<div class="form-actions"><button class="primary">Test repository</button><a href="/setup/guide">How do I connect this repository to Jules?</a></div></form><form method="post" action="/setup/refresh-sources" class="inline-form">${csrf(csrfToken)}<button class="ghost">I’ve connected it — retry discovery</button></form>`;
}

function defaultsStep({ binding, folders = [], defaults = {}, error, csrfToken, nextProjectNumber }) {
  return `<div class="eyebrow">Step 03 / 03</div><h1>Set your defaults</h1><p class="lead">These guide new research projects. You can change them later.</p>${notice(error)}<div class="binding-card"><span class="status good">Verified destination</span><h2>${esc(binding.github_full_name)}</h2><p>Base branch <strong>${esc(binding.base_branch)}</strong> · Jules and GitHub connected</p><p>${folders.length} existing numbered projects · next project <strong>${nextProjectNumber ?? nextNumber(folders)}</strong></p></div><form method="post" action="/setup/defaults" class="form-card">${csrf(csrfToken)}<div class="field-grid"><div><label for="runtime">Preferred runtime</label><select id="runtime" name="runtime"><option value="30–60" ${defaults.runtime === '30–60' ? 'selected' : ''}>30–60 minutes</option><option value="15–30" ${defaults.runtime === '15–30' ? 'selected' : ''}>15–30 minutes</option><option value="60–120" ${defaults.runtime === '60–120' ? 'selected' : ''}>60–120 minutes</option></select></div><div><label for="concurrency">Default concurrency</label><input id="concurrency" name="concurrency" type="number" min="1" max="60" value="${attr(defaults.concurrency ?? 10)}" required></div><div><label for="developmentSeeds">Development seeds</label><input id="developmentSeeds" name="developmentSeeds" type="number" min="1" max="100" value="${attr(defaults.developmentSeeds ?? 5)}" required></div><div><label for="finalSeeds">Final seeds</label><input id="finalSeeds" name="finalSeeds" type="number" min="1" max="100" value="${attr(defaults.finalSeeds ?? 10)}" required></div></div><div class="form-actions"><button class="primary">Finish setup</button></div></form>`;
}

export function setupPage(options) {
  const { stepNumber, binding } = options;
  const progress = `<div class="steps">${step(1, 'Jules', stepNumber)}${step(2, 'Repository', stepNumber)}${step(3, 'Defaults', stepNumber)}</div>`;
  let content = stepNumber === 1 ? julesConnectionStep(options) : stepNumber === 2 ? repositoryConnectionStep(options) : defaultsStep(options);
  if (stepNumber === 3) content += '<p class="help">You can <a href="/prompt">edit the full research prompt</a> before launching any task.</p>';
  return layout('Setup', `<main class="setup"><div class="setup-intro"><span class="eyebrow">First run</span><div class="progress-title">Connect Jules and GitHub</div>${progress}</div><section class="setup-main">${content}</section></main>`, { configured: !!binding });
}
function sameSource(source, prefill) { return prefill.sourceName === source.name || !prefill.sourceName && prefill.owner && String(source.githubRepo.owner).toLowerCase() === String(prefill.owner).toLowerCase() && String(source.githubRepo.repo).toLowerCase() === String(prefill.repo).toLowerCase(); }

export function guidePage(csrfToken) {
  return layout('Connect a repository to Jules', `<main class="narrow"><a class="back" href="/setup">← Back to setup</a><div class="eyebrow">Repository access</div><h1>Connect your repository to Jules</h1><p class="lead">Jules currently adds GitHub sources through its web app. Its API can list connected sources but cannot create them.</p><ol class="guide-list"><li>Open <a href="https://jules.google.com/" target="_blank" rel="noopener">Jules ↗</a> and sign in.</li><li>Use the repository selector and choose <strong>+ Add repository</strong>. If GitHub is not connected yet, choose <strong>Connect to GitHub account</strong>.</li><li>On GitHub, grant the Google Labs Jules app access to the repository and save.</li><li>Return here and retry discovery.</li></ol><p class="help">You can also manage access under GitHub Settings → Applications → Google Labs Jules → Configure.</p><form method="post" action="/setup/refresh-sources">${csrf(csrfToken)}<button class="primary">I’ve connected it — retry</button></form><p class="source-note">Instructions follow the <a href="https://jules.google/docs/tasks-repos" target="_blank" rel="noopener">current Jules repository guide ↗</a>.</p></main>`);
}
