import { layout } from './layout.mjs';
import { icon } from './icons.mjs';
import { esc, attr, link, csrf, notice, statusClass, nextNumber } from './ui-helpers.mjs';

export { layout, styleHash } from './layout.mjs';
const repositoryHelp = error => error?.startsWith('Could not locate') || error?.includes('saved source identifier has changed') ? `<section class="panel"><h2>Reconnect the repository</h2><p>Open Jules with the account that created this API key. Find the repository in its selector, or use Add repository to connect it. Then verify the destination here.</p><div class="form-actions"><a class="button primary" href="/setup?rebind=1">Choose an available repository</a><a href="https://jules.google.com/" target="_blank" rel="noopener">Open Jules</a><a href="/setup/guide">Repository setup instructions</a></div></section>` : '';


export { setupPage, guidePage } from './setup-ui.mjs';

function projectClearControls(projects, csrfToken) {
  const clearGroups = [
    { id: 'finished', label: 'finished', statuses: ['pr_validated', 'completed', 'completed_no_pr'] },
    { id: 'reserved', label: 'reserved', statuses: ['reserved'] },
    { id: 'failed', label: 'failed', statuses: ['failed', 'blocked', 'pr_rejected'] },
    { id: 'stopped', label: 'stopped', statuses: ['stopped'] }
  ];
  return `<div class="project-clear"><p>Clear local records by status. This removes their saved activity here; Jules sessions and GitHub pull requests stay available.</p><div class="project-clear-actions">${clearGroups.map(group => {
    const count = projects.filter(project => group.statuses.includes(project.status) && (group.id !== 'reserved' || !project.jules_session_name)).length;
    return `<form method="post" action="/projects/clear">${csrf(csrfToken)}<input type="hidden" name="category" value="${group.id}"><button class="ghost" ${count ? '' : 'disabled'}>Clear ${group.label} (${count})</button></form>`;
  }).join('')}</div></div>`;
}

function projectRow(project, binding, csrfToken) {
  const canRemove = project.status === 'reserved' && !project.jules_session_name;
  const remove = canRemove ? `<form method="post" action="/projects/remove" class="remove-reservation">${csrf(csrfToken)}<input type="hidden" name="projectId" value="${attr(project.id)}"><button class="ghost" type="submit" aria-label="Remove reservation for ${attr(project.folder)}">Remove reservation</button></form>` : '';
  const review = canRemove ? `${link(`/preflight?id=${encodeURIComponent(project.id)}`, 'Review & launch')} · ` : '';
  const links = `${review}<a href="/projects/${attr(project.id)}">Inspect</a>${project.jules_session_url ? ` · ${link(project.jules_session_url, 'Jules ↗')}` : ''}${project.pr_url ? ` · ${link(project.pr_url, 'PR ↗')}` : ''}`;
  return `<tr><td><strong>${esc(project.folder)}/</strong><small>${esc(project.topic)}${project.repository_full_name && project.repository_full_name !== binding.github_full_name ? ` · ${esc(project.repository_full_name)}` : ''}</small></td><td><span class="status ${statusClass(project)}">${esc(project.status.replaceAll('_', ' '))}</span>${project.pr_status ? `<small>PR ${esc(project.pr_status)}</small>` : ''}</td><td>${links}${remove}</td></tr>${project.error ? `<tr class="error-row"><td colspan="3">${esc(project.error)}</td></tr>` : ''}`;

}

export function dashboardPage({ binding, folders, projects, csrfToken, message, error, defaults, nextProjectNumber }) {
  const next = nextProjectNumber ?? nextNumber(folders, projects);
  const clearControls = projectClearControls(projects, csrfToken);
  const rows = projects.map(project => projectRow(project, binding, csrfToken)).join('');
  return layout('Projects', `<main class="dashboard"><div class="page-heading"><div><span class="eyebrow">Workspace</span><h1>Research projects</h1><p class="lead">Reserve a folder for each topic, review the destination, then launch Jules.</p></div><div class="repo-summary"><span class="status good">Connected repository</span><strong>${esc(binding.github_full_name)}</strong><span>${esc(binding.base_branch)} · Jules ${icon('check')} · GitHub ${icon('check')}</span></div></div>${notice(error)}${notice(message, 'success')}<div class="metrics"><div><span>Existing projects</span><strong>${folders.length}</strong></div><div><span>Next project number</span><strong>${next}</strong><a class="metric-link" href="/settings#project-number">Change number</a></div><div><span>Concurrency</span><strong>${esc(defaults.concurrency)}</strong></div></div><section class="workspace-grid"><div class="panel"><div class="panel-heading"><h2>New topics</h2><span>One topic per line</span></div><form method="post" action="/projects/reserve">${csrf(csrfToken)}<label for="topics">Research topics</label><textarea id="topics" name="topics" rows="8" required placeholder="Uncertainty Estimation&#10;Concept Drift&#10;Robust Regression"></textarea><div class="form-actions"><button class="primary">Reserve directories</button></div></form></div><div class="panel"><div class="panel-heading"><h2>Repository preview</h2>${link(`https://github.com/${binding.github_full_name}/tree/${encodeURIComponent(binding.base_branch)}`, 'Open repository ↗')}</div><div class="folder-list">${folders.length ? folders.slice(0, 12).map(item => `<span>${esc(item.name)}/</span>`).join('') : '<p>No numbered folders found on this branch.</p>'}</div><p class="help">${folders.length > 12 ? `Showing 12 of ${folders.length}. ` : ''}New folders start at ${next}.</p></div></section><section class="panel projects"><div class="panel-heading"><h2>Reserved and launched</h2><span>${projects.length} local projects</span></div>${clearControls}${rows ? `<div class="table-wrap"><table><thead><tr><th>Assigned folder</th><th>Status</th><th>Links</th></tr></thead><tbody>${rows}</tbody></table></div>` : '<div class="empty">No projects yet. Add topics above to begin.</div>'}</section></main>`, { configured: true });
}

export function preflightPage({ binding, projects, csrfToken, error, valid, prompts = [] }) {
  const promptReview = prompts.map((prompt, index) => `<details class="panel prompt-snapshot"><summary>Prompt for ${esc(projects[index].folder)}/</summary><pre>${esc(prompt)}</pre></details>`).join('');
  return layout('Preflight', `<main class="narrow"><a class="back" href="/">← Back to projects</a><div class="eyebrow">Launch preflight</div><h1>Review the destination</h1><p class="lead">These are the repository, directories, and instructions Jules will use.</p>${notice(error)}<div class="preflight-card"><div><span>Repository</span><strong>${esc(binding.github_full_name)}</strong></div><div><span>Base branch</span><strong>${esc(binding.base_branch)}</strong></div><div><span>Jules connection</span><strong>${valid ? `${icon('check')} Verified` : 'Needs attention'}</strong></div><div><span>GitHub connection</span><strong>${valid ? `${icon('check')} Verified` : 'Needs attention'}</strong></div><div><span>Projects</span><strong>${projects.length}</strong></div></div><div class="panel"><h2>Assigned folders</h2><ol class="assigned">${projects.map(project => `<li><strong>${esc(project.folder)}/</strong><span>${esc(project.topic)}</span></li>`).join('')}</ol></div>${promptReview}<p class="help">Need to change the instructions? <a href="/prompt">Edit the prompt template</a>, then return to this review.</p>${valid ? `<form method="post" action="/projects/launch" class="launch-actions">${csrf(csrfToken)}${projects.map(project => `<input type="hidden" name="projectId" value="${attr(project.id)}">`).join('')}<a class="button ghost" href="/">Cancel</a><button class="primary">Launch ${projects.length} Jules task${projects.length === 1 ? '' : 's'}</button></form>` : `<div class="launch-actions"><a class="button ghost" href="/settings">Repair binding</a></div>`}</main>`, { configured: true });
}

export function settingsPage({ binding, folders, projects, defaults, csrfToken, message, error, nextProjectNumber }) {
  const nextNumberForm = `<section class="panel project-number-settings" id="project-number"><h2>Next project number</h2><p>Start a new numbering series when older project folders have been moved out of the repository root. Existing local history remains available. Research Facility checks the current root folders before reserving a number.</p><form method="post" action="/settings/next-number">${csrf(csrfToken)}<label for="nextProjectNumber">Number for the next project</label><div class="project-number-row"><input id="nextProjectNumber" name="nextProjectNumber" type="number" min="1" max="1000000" step="1" value="${attr(nextProjectNumber ?? nextNumber(folders, projects))}" required><button class="primary">Set next number</button></div></form><p class="help">Clear old reservations and finish or stop active tasks before changing this number.</p></section>`;
  const julesKeyForm = `<section class="panel" id="jules-key"><h2>Update Jules key</h2><p>Jules and NVIDIA use separate API keys. If Jules reports an invalid key, replace it here. The new key is checked against this repository before it is saved.</p><form method="post" action="/settings/jules">${csrf(csrfToken)}<label for="julesKey">New Jules API key</label><input id="julesKey" name="julesKey" type="password" autocomplete="off" required><div class="form-actions"><button class="primary">Verify and update Jules key</button><a href="https://jules.google.com/settings" target="_blank" rel="noopener">Get a Jules key ↗</a></div></form></section>`;
  return layout('Connection', `<main class="narrow"><div class="eyebrow">Settings</div><h1>Repository connection</h1><p class="lead">The destination is checked again before every Jules task.</p>${notice(error)}${repositoryHelp(error)}${notice(message, 'success')}<div class="binding-card"><span class="status good">Connected</span><h2>${esc(binding.github_full_name)}</h2><p>Branch: <strong>${esc(binding.base_branch)}</strong></p><p>Jules ${icon('check')} Connected · GitHub ${icon('check')} Connected</p><p>${folders.length} existing projects · next ID ${nextProjectNumber ?? nextNumber(folders, projects)}</p></div><div class="settings-actions"><form method="post" action="/settings/test">${csrf(csrfToken)}<button class="primary">Test connections</button></form><form method="post" action="/settings/refresh">${csrf(csrfToken)}<button class="ghost">Refresh repository</button></form><a class="button ghost" href="/setup?rebind=1">Change repository</a></div><div class="panel"><h2>Defaults</h2><p>Runtime ${esc(defaults.runtime)} min · Development seeds ${esc(defaults.developmentSeeds)} · Final seeds ${esc(defaults.finalSeeds)} · Concurrency ${esc(defaults.concurrency)}</p><a href="/activity/settings">Edit agent settings</a></div>${nextNumberForm}${julesKeyForm}<div class="panel saved-setup"><h2>Saved setup</h2><p>Your connection, credentials, defaults, projects, and agent activity are saved locally in <code>.data/</code> and restored when you restart Research Facility. Credentials are encrypted. For a fresh checkout, fill in <code>.env.local</code> using <code>.env.example</code>.</p><p>The active research instructions are in <code>prompt-template.txt</code>; saved prompts are in <code>.data/</code>.</p><a href="/prompt">Choose research prompt →</a></div></main>`, { configured: true });
}

export { esc };
