import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join } from 'node:path';
import { icon, brandSymbol } from './icons.mjs';

const stylesheet = readFileSync(join(import.meta.dirname, '..', 'public', 'style.css'), 'utf8');
export const styleHash = createHash('sha256').update(stylesheet).digest('base64');

const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
const attr = esc;
const link = (href, label) => `<a href="${attr(href)}">${esc(label)}</a>`;
const csrf = token => `<input type="hidden" name="csrf" value="${attr(token)}">`;
const notice = (message, kind = 'action') => message ? `<div class="notice ${kind}" role="status">${esc(message)}</div>` : '';
const repositoryHelp = error => error?.startsWith('Could not locate') || error?.includes('saved source identifier has changed') ? `<section class="panel"><h2>Reconnect the repository</h2><p>Open Jules with the account that created this API key. Find the repository in its selector, or use Add repository to connect it. Then verify the destination here.</p><div class="form-actions"><a class="button primary" href="/setup?rebind=1">Choose an available repository</a><a href="https://jules.google.com/" target="_blank" rel="noopener">Open Jules</a><a href="/setup/guide">Repository setup instructions</a></div></section>` : '';
const step = (n, title, current) => `<div class="step ${n === current ? 'current' : n < current ? 'done' : ''}"><span>${n}</span>${esc(title)}</div>`;

export function layout(title, body, { configured = false, refresh = false, autoRefresh = false, landing = false } = {}) {
  const activeTitle = { '/welcome': 'Research automation', '/': 'Projects', '/activity': 'Jules agents', '/orchestrator': 'Research orchestrator', '/prompt': 'Research prompt', '/settings': 'Connection' };
  const navLink = (href, label) => `<a href="${href}"${title === activeTitle[href] ? ' aria-current="page"' : ''}>${label}</a>`;
  const navigation = configured ? `${navLink('/welcome', 'Overview')}${navLink('/', 'Projects')}${navLink('/activity', 'Agents')}${navLink('/orchestrator', 'Orchestrator')}${navLink('/prompt', 'Prompt')}${navLink('/settings', 'Connection')}` : `<a href="/welcome">Overview</a><a aria-current="page" href="/setup">Connect workspace</a>`;
  // Give existing directional links the same Lucide treatment as the new screens.
  const content = body.replace(/<div class="notice([^"]*)"([^>]*)>([\s\S]*?)<\/div>/g, (match, classes, attrs, content) => `<div class="notice ${classes.includes('success') ? 'success' : /denied|rejected|forbidden|failed|invalid|mismatch|did not return/i.test(content.replace(/<[^>]*>/g, '')) ? 'error' : 'action'}"${attrs}>${content}</div>`).replace(/(<a\b[^>]*>)([^<]*)(<\/a>)/g, (match, start, label, end) => {
    if (label.startsWith('← ')) return `${start}${icon('arrow-left')} ${label.slice(2)}${end}`;
    if (/[↗→]$/.test(label)) return `${start}${label.slice(0, -1).trimEnd()} ${icon(label.endsWith('↗') ? 'arrow-up-right' : 'arrow-right')}${end}`;
    return match;
  });
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#f5f4ed"><meta name="description" content="Automate research with NVIDIA and Jules. Create task plans and submit reports with sources to your GitHub repository.">${autoRefresh ? '<meta http-equiv="refresh" content="20">' : ''}<title>${esc(title)} · Research Facility</title><link rel="icon" type="image/svg+xml" href="/favicon.svg"><link rel="preload" href="/fonts/manrope.ttf" as="font" type="font/ttf" crossorigin><link rel="preload" href="/fonts/fraunces.ttf" as="font" type="font/ttf" crossorigin><script src="/theme.js"></script><style>${stylesheet}</style><script src="/interface.js" defer></script></head><body class="${landing ? 'landing-page' : 'workspace-page'}"><a class="skip-link" href="#main-content">Skip to content</a><div class="shell"><header class="topbar"><div class="brand"><button class="theme-toggle" type="button" data-theme-toggle aria-label="Switch color theme" aria-pressed="false">${brandSymbol}</button><a class="brand-link" href="/welcome">Research Facility</a></div>${landing ? '' : `<nav aria-label="Primary navigation">${navigation}</nav>`}</header>${content.replace('<main', '<main id="main-content"')}</div></body></html>`;
}

export function setupPage({ stepNumber, sources = [], binding, folders = [], defaults = {}, error, branches = [], csrfToken, prefill = {}, rebind = false, connectedJules = false, nextProjectNumber }) {
  const progress = `<div class="steps">${step(1, 'Jules', stepNumber)}${step(2, 'Repository', stepNumber)}${step(3, 'Defaults', stepNumber)}</div>`;
  let content = '';
  if (stepNumber === 1) {
    content = `<div class="eyebrow">Step 01 / 03</div><h1>Connect Jules</h1><p class="lead">Paste your Jules API key. Research Facility will discover the repositories it can access.</p>${notice(error)}<form method="post" action="/setup/jules" class="form-card">${csrf(csrfToken)}<label for="julesKey">Jules API key</label><input id="julesKey" name="julesKey" type="password" required autocomplete="off" placeholder="Paste API key"><div class="form-actions"><button class="primary">Test Jules connection</button><a href="https://jules.google.com/settings" target="_blank" rel="noopener">Get an API key ↗</a></div></form><p class="help">The key is sent only to this local server and is never shown again.</p>`;
  } else if (stepNumber === 2) {
    const options = sources.map(source => `<label class="repo-option"><input type="radio" name="sourceName" value="${attr(source.name)}" ${sameSource(source, prefill) ? 'checked' : ''}><span><strong>${esc(source.githubRepo.owner)}/${esc(source.githubRepo.repo)}</strong><small>${esc(source.githubRepo.defaultBranch?.displayName ?? 'GitHub repository')}</small></span></label>`).join('');
    content = `<div class="eyebrow">Step 02 / 03</div><h1>Choose the destination</h1><p class="lead">Select the repository Jules should work on, then verify GitHub access and the base branch.</p>${notice(error)}${error?.startsWith('Could not locate') ? '<div class="diagnostic"><strong>Check these common causes</strong><ul><li>Jules has not been granted access to this repository.</li><li>The GitHub account connected to Jules cannot see it.</li><li>The repository has not been added as a Jules source.</li></ul><a href="/setup/guide">Show setup instructions →</a></div>' : ''}${connectedJules ? notice(`Jules connected · ${sources.length} repositories available`, 'success') : ''}<form method="post" action="/setup/repository" class="form-card">${csrf(csrfToken)}${rebind ? '<input type="hidden" name="rebind" value="1">' : ''}${options ? `<fieldset><legend>Repositories available to Jules</legend><div class="repo-list">${options}<label class="repo-option"><input type="radio" name="sourceName" value="__manual__"><span><strong>Enter a repository manually</strong><small>Research Facility will locate it in Jules</small></span></label></div></fieldset>` : `<div class="empty">No Jules repositories are currently available. Connect the repository in Jules, then retry discovery.</div>`}<details class="fallback" ${!options ? 'open' : ''}><summary>GitHub owner and repository</summary><div class="field-grid"><div><label for="owner">GitHub owner</label><input id="owner" name="owner" value="${attr(prefill.owner ?? '')}" placeholder="example-owner"></div><div><label for="repo">Repository</label><input id="repo" name="repo" value="${attr(prefill.repo ?? '')}" placeholder="example-research-repo"></div></div><p class="help">Research Facility still resolves the Jules source from the official API. Select “Enter a repository manually” above when using these fields.</p></details><div class="field-grid"><div><label for="branch">Base branch</label><input id="branch" name="branch" value="${attr(prefill.branch ?? 'main')}" required></div><div><label for="githubToken">GitHub token</label><input id="githubToken" name="githubToken" type="password" autocomplete="off" placeholder="${binding ? 'Leave blank to keep current token' : 'Fine-grained token'}" ${binding ? '' : 'required'}></div></div>${branches.length ? `<div class="branch-choices"><strong>Available branches</strong>${branches.map(name => `<label><input type="radio" name="branchChoice" value="${attr(name)}">${esc(name)}</label>`).join('')}</div>` : ''}<div class="form-actions"><button class="primary">Test repository</button><a href="/setup/guide">How do I connect this repository to Jules?</a></div></form><form method="post" action="/setup/refresh-sources" class="inline-form">${csrf(csrfToken)}<button class="ghost">I’ve connected it — retry discovery</button></form>`;
  } else {
    content = `<div class="eyebrow">Step 03 / 03</div><h1>Set your defaults</h1><p class="lead">These guide new research projects. You can change them later.</p>${notice(error)}<div class="binding-card"><span class="status good">Verified destination</span><h2>${esc(binding.github_full_name)}</h2><p>Base branch <strong>${esc(binding.base_branch)}</strong> · Jules and GitHub connected</p><p>${folders.length} existing numbered projects · next project <strong>${nextProjectNumber ?? nextNumber(folders)}</strong></p></div><form method="post" action="/setup/defaults" class="form-card">${csrf(csrfToken)}<div class="field-grid"><div><label for="runtime">Preferred runtime</label><select id="runtime" name="runtime"><option value="30–60" ${defaults.runtime === '30–60' ? 'selected' : ''}>30–60 minutes</option><option value="15–30" ${defaults.runtime === '15–30' ? 'selected' : ''}>15–30 minutes</option><option value="60–120" ${defaults.runtime === '60–120' ? 'selected' : ''}>60–120 minutes</option></select></div><div><label for="concurrency">Default concurrency</label><input id="concurrency" name="concurrency" type="number" min="1" max="60" value="${attr(defaults.concurrency ?? 10)}" required></div><div><label for="developmentSeeds">Development seeds</label><input id="developmentSeeds" name="developmentSeeds" type="number" min="1" max="100" value="${attr(defaults.developmentSeeds ?? 5)}" required></div><div><label for="finalSeeds">Final seeds</label><input id="finalSeeds" name="finalSeeds" type="number" min="1" max="100" value="${attr(defaults.finalSeeds ?? 10)}" required></div></div><div class="form-actions"><button class="primary">Finish setup</button></div></form>`;
  }
  if (stepNumber === 3) content += '<p class="help">You can <a href="/prompt">edit the full research prompt</a> before launching any task.</p>';
  return layout('Setup', `<main class="setup"><div class="setup-intro"><span class="eyebrow">First run</span><div class="progress-title">Connect Jules and GitHub</div>${progress}</div><section class="setup-main">${content}</section></main>`, { configured: !!binding });
}
function sameSource(source, prefill) { return prefill.sourceName === source.name || !prefill.sourceName && prefill.owner && String(source.githubRepo.owner).toLowerCase() === String(prefill.owner).toLowerCase() && String(source.githubRepo.repo).toLowerCase() === String(prefill.repo).toLowerCase(); }
function nextNumber(folders, projects = []) { return Math.max(0, ...folders.map(item => item.number), ...projects.map(item => item.folder_number)) + 1; }

export function guidePage(csrfToken) {
  return layout('Connect a repository to Jules', `<main class="narrow"><a class="back" href="/setup">← Back to setup</a><div class="eyebrow">Repository access</div><h1>Connect your repository to Jules</h1><p class="lead">Jules currently adds GitHub sources through its web app. Its API can list connected sources but cannot create them.</p><ol class="guide-list"><li>Open <a href="https://jules.google.com/" target="_blank" rel="noopener">Jules ↗</a> and sign in.</li><li>Use the repository selector and choose <strong>+ Add repository</strong>. If GitHub is not connected yet, choose <strong>Connect to GitHub account</strong>.</li><li>On GitHub, grant the Google Labs Jules app access to the repository and save.</li><li>Return here and retry discovery.</li></ol><p class="help">You can also manage access under GitHub Settings → Applications → Google Labs Jules → Configure.</p><form method="post" action="/setup/refresh-sources">${csrf(csrfToken)}<button class="primary">I’ve connected it — retry</button></form><p class="source-note">Instructions follow the <a href="https://jules.google/docs/tasks-repos" target="_blank" rel="noopener">current Jules repository guide ↗</a>.</p></main>`);
}

export function dashboardPage({ binding, folders, projects, csrfToken, message, error, defaults, nextProjectNumber }) {
  const next = nextProjectNumber ?? nextNumber(folders, projects);
  const clearGroups = [
    { id: 'finished', label: 'finished', statuses: ['pr_validated', 'completed', 'completed_no_pr'] },
    { id: 'reserved', label: 'reserved', statuses: ['reserved'] },
    { id: 'failed', label: 'failed', statuses: ['failed', 'blocked', 'pr_rejected'] },
    { id: 'stopped', label: 'stopped', statuses: ['stopped'] }
  ];
  const clearControls = `<div class="project-clear"><p>Clear local records by status. This removes their saved activity here; Jules sessions and GitHub pull requests stay available.</p><div class="project-clear-actions">${clearGroups.map(group => {
    const count = projects.filter(project => group.statuses.includes(project.status) && (group.id !== 'reserved' || !project.jules_session_name)).length;
    return `<form method="post" action="/projects/clear">${csrf(csrfToken)}<input type="hidden" name="category" value="${group.id}"><button class="ghost" ${count ? '' : 'disabled'}>Clear ${group.label} (${count})</button></form>`;
  }).join('')}</div></div>`;
  const rows = projects.map(project => {
    const canRemove = project.status === 'reserved' && !project.jules_session_name;
    const remove = canRemove ? `<form method="post" action="/projects/remove" class="remove-reservation">${csrf(csrfToken)}<input type="hidden" name="projectId" value="${attr(project.id)}"><button class="ghost" type="submit" aria-label="Remove reservation for ${attr(project.folder)}">Remove reservation</button></form>` : '';
    const review = canRemove ? `${link(`/preflight?id=${encodeURIComponent(project.id)}`, 'Review & launch')} · ` : '';
    const links = `${review}<a href="/projects/${attr(project.id)}">Inspect</a>${project.jules_session_url ? ` · ${link(project.jules_session_url, 'Jules ↗')}` : ''}${project.pr_url ? ` · ${link(project.pr_url, 'PR ↗')}` : ''}`;
    return `<tr><td><strong>${esc(project.folder)}/</strong><small>${esc(project.topic)}${project.repository_full_name && project.repository_full_name !== binding.github_full_name ? ` · ${esc(project.repository_full_name)}` : ''}</small></td><td><span class="status ${['failed','blocked','pr_rejected'].includes(project.status) ? 'bad' : ['completed','pr_validated'].includes(project.status) ? 'good' : ''}">${esc(project.status.replaceAll('_', ' '))}</span>${project.pr_status ? `<small>PR ${esc(project.pr_status)}</small>` : ''}</td><td>${links}${remove}</td></tr>${project.error ? `<tr class="error-row"><td colspan="3">${esc(project.error)}</td></tr>` : ''}`;
  }).join('');
  return layout('Projects', `<main class="dashboard"><div class="page-heading"><div><span class="eyebrow">Workspace</span><h1>Research projects</h1><p class="lead">Reserve a folder for each topic, review the destination, then launch Jules.</p></div><div class="repo-summary"><span class="status good">Connected repository</span><strong>${esc(binding.github_full_name)}</strong><span>${esc(binding.base_branch)} · Jules ${icon('check')} · GitHub ${icon('check')}</span></div></div>${notice(error)}${notice(message, 'success')}<div class="metrics"><div><span>Existing projects</span><strong>${folders.length}</strong></div><div><span>Next project number</span><strong>${next}</strong><a class="metric-link" href="/settings#project-number">Change number</a></div><div><span>Concurrency</span><strong>${esc(defaults.concurrency)}</strong></div></div><section class="workspace-grid"><div class="panel"><div class="panel-heading"><h2>New topics</h2><span>One topic per line</span></div><form method="post" action="/projects/reserve">${csrf(csrfToken)}<label for="topics">Research topics</label><textarea id="topics" name="topics" rows="8" required placeholder="Uncertainty Estimation&#10;Concept Drift&#10;Robust Regression"></textarea><div class="form-actions"><button class="primary">Reserve directories</button></div></form></div><div class="panel"><div class="panel-heading"><h2>Repository preview</h2>${link(`https://github.com/${binding.github_full_name}/tree/${encodeURIComponent(binding.base_branch)}`, 'Open repository ↗')}</div><div class="folder-list">${folders.length ? folders.slice(0, 12).map(item => `<span>${esc(item.name)}/</span>`).join('') : '<p>No numbered folders found on this branch.</p>'}</div><p class="help">${folders.length > 12 ? `Showing 12 of ${folders.length}. ` : ''}New folders start at ${next}.</p></div></section><section class="panel projects"><div class="panel-heading"><h2>Reserved and launched</h2><span>${projects.length} local projects</span></div>${clearControls}${rows ? `<div class="table-wrap"><table><thead><tr><th>Assigned folder</th><th>Status</th><th>Links</th></tr></thead><tbody>${rows}</tbody></table></div>` : '<div class="empty">No projects yet. Add topics above to begin.</div>'}</section></main>`, { configured: true, refresh: projects.some(project => ['queued','launching','running'].includes(project.status)) });
}

export function preflightPage({ binding, projects, csrfToken, error, valid, prompts = [] }) {
  const promptReview = prompts.map((prompt, index) => `<details class="panel prompt-snapshot"><summary>Prompt for ${esc(projects[index].folder)}/</summary><pre>${esc(prompt)}</pre></details>`).join('');
  return layout('Preflight', `<main class="narrow"><a class="back" href="/">← Back to projects</a><div class="eyebrow">Launch preflight</div><h1>Review the destination</h1><p class="lead">These are the repository, directories, and instructions Jules will use.</p>${notice(error)}<div class="preflight-card"><div><span>Repository</span><strong>${esc(binding.github_full_name)}</strong></div><div><span>Base branch</span><strong>${esc(binding.base_branch)}</strong></div><div><span>Jules connection</span><strong>${valid ? `${icon('check')} Verified` : 'Needs attention'}</strong></div><div><span>GitHub connection</span><strong>${valid ? `${icon('check')} Verified` : 'Needs attention'}</strong></div><div><span>Projects</span><strong>${projects.length}</strong></div></div><div class="panel"><h2>Assigned folders</h2><ol class="assigned">${projects.map(project => `<li><strong>${esc(project.folder)}/</strong><span>${esc(project.topic)}</span></li>`).join('')}</ol></div>${promptReview}<p class="help">Need to change the instructions? <a href="/prompt">Edit the prompt template</a>, then return to this review.</p>${valid ? `<form method="post" action="/projects/launch" class="launch-actions">${csrf(csrfToken)}${projects.map(project => `<input type="hidden" name="projectId" value="${attr(project.id)}">`).join('')}<a class="button ghost" href="/">Cancel</a><button class="primary">Launch ${projects.length} Jules task${projects.length === 1 ? '' : 's'}</button></form>` : `<div class="launch-actions"><a class="button ghost" href="/settings">Repair binding</a></div>`}</main>`, { configured: true });
}

export function settingsPage({ binding, folders, projects, defaults, csrfToken, message, error, nextProjectNumber }) {
  const nextNumberForm = `<section class="panel project-number-settings" id="project-number"><h2>Next project number</h2><p>Start a new numbering series when older project folders have been moved out of the repository root. Existing local history remains available. Research Facility checks the current root folders before reserving a number.</p><form method="post" action="/settings/next-number">${csrf(csrfToken)}<label for="nextProjectNumber">Number for the next project</label><div class="project-number-row"><input id="nextProjectNumber" name="nextProjectNumber" type="number" min="1" max="1000000" step="1" value="${attr(nextProjectNumber ?? nextNumber(folders, projects))}" required><button class="primary">Set next number</button></div></form><p class="help">Clear old reservations and finish or stop active tasks before changing this number.</p></section>`;
  const julesKeyForm = `<section class="panel" id="jules-key"><h2>Update Jules key</h2><p>Jules and NVIDIA use separate API keys. If Jules reports an invalid key, replace it here. The new key is checked against this repository before it is saved.</p><form method="post" action="/settings/jules">${csrf(csrfToken)}<label for="julesKey">New Jules API key</label><input id="julesKey" name="julesKey" type="password" autocomplete="off" required><div class="form-actions"><button class="primary">Verify and update Jules key</button><a href="https://jules.google.com/settings" target="_blank" rel="noopener">Get a Jules key ↗</a></div></form></section>`;
  return layout('Connection', `<main class="narrow"><div class="eyebrow">Settings</div><h1>Repository connection</h1><p class="lead">The destination is checked again before every Jules task.</p>${notice(error)}${repositoryHelp(error)}${notice(message, 'success')}<div class="binding-card"><span class="status good">Connected</span><h2>${esc(binding.github_full_name)}</h2><p>Branch: <strong>${esc(binding.base_branch)}</strong></p><p>Jules ${icon('check')} Connected · GitHub ${icon('check')} Connected</p><p>${folders.length} existing projects · next ID ${nextProjectNumber ?? nextNumber(folders, projects)}</p></div><div class="settings-actions"><form method="post" action="/settings/test">${csrf(csrfToken)}<button class="primary">Test connections</button></form><form method="post" action="/settings/refresh">${csrf(csrfToken)}<button class="ghost">Refresh repository</button></form><a class="button ghost" href="/setup?rebind=1">Change repository</a></div><div class="panel"><h2>Defaults</h2><p>Runtime ${esc(defaults.runtime)} min · Development seeds ${esc(defaults.developmentSeeds)} · Final seeds ${esc(defaults.finalSeeds)} · Concurrency ${esc(defaults.concurrency)}</p><a href="/activity/settings">Edit agent settings</a></div>${nextNumberForm}${julesKeyForm}<div class="panel saved-setup"><h2>Saved setup</h2><p>Your connection, credentials, defaults, projects, and agent activity are saved locally in <code>.data/</code> and restored when you restart Research Facility. Credentials are encrypted. For a fresh checkout, fill in <code>.env.local</code> using <code>.env.example</code>.</p><p>The active research instructions are in <code>prompt-template.txt</code>; saved prompts are in <code>.data/</code>.</p><a href="/prompt">Choose research prompt →</a></div></main>`, { configured: true });
}

export { esc };
