import { layout } from './layout.mjs';
import { esc, csrf, notice, label, date, active, statusClass } from './ui-helpers.mjs';


export function promptPage({ template, library, csrfToken, error, message, configured, back, promptName = '' }) {
  const activePrompt = library.presets.find(preset => preset.id === library.activeId);
  const saved = library.presets.map(preset => `<div class="prompt-preset"><div><strong>${esc(preset.name)}</strong>${preset.id === library.activeId ? '<span class="status good">Active</span>' : ''}</div>${preset.id === library.activeId ? '<span class="prompt-preset-note">Used for new launches</span>' : `<form method="post" action="/prompt/activate">${csrf(csrfToken)}<input type="hidden" name="promptId" value="${esc(preset.id)}"><button class="ghost" type="submit">Use this prompt</button></form>`}</div>`).join('');
  return layout('Research prompt', `<main class="narrow"><a class="back" href="${esc(back)}">← Back</a><div class="eyebrow">Prompt library</div><h1>Research instructions for Jules</h1><p class="lead">Choose a saved prompt for new tasks. Each launched task keeps the exact instructions it received, even if you switch prompts later.</p>${notice(error, 'action', 'alert')}${notice(message, 'success')}<section class="panel prompt-library"><h2>Saved prompts</h2><p class="help">Save changes before switching prompts. The selected prompt is shown in preflight and sent to Jules.</p><div class="prompt-preset-list">${saved}</div></section><form method="post" action="/prompt" class="panel prompt-form">${csrf(csrfToken)}<h2>Edit ${esc(activePrompt?.name ?? 'active prompt')}</h2><label for="promptTemplate">Prompt template</label><textarea id="promptTemplate" name="promptTemplate" class="prompt-editor" spellcheck="false" required>${esc(template)}</textarea><p class="help">The active version is also saved in <strong>prompt-template.txt</strong>. Keep {{topic}}, {{repository}}, {{branch}}, and {{folder}}. Optional: {{runtime}}, {{development_seeds}}, {{final_seeds}}.</p><div class="form-actions"><button class="primary" name="action" value="save">Save changes</button></div><div class="prompt-save-as"><label for="promptName">Save a separate copy</label><div class="prompt-save-row"><input id="promptName" name="promptName" value="${esc(promptName)}" maxlength="80" placeholder="Name this prompt"><button class="ghost" name="action" value="save-as">Save as new</button></div></div></form></main>`, { configured });
}

function agentCard(project, item) {
  return `<article class="agent-card"><div class="agent-card-top"><div><span class="eyebrow">${esc(project.folder)}/</span><h2><a href="/projects/${esc(project.id)}">${esc(project.topic)}</a></h2></div><span class="status ${statusClass(project)}">${esc(project.jules_state ? label(project.jules_state) : label(project.status))}</span></div><p class="agent-meta">${esc(project.repository_full_name)} · ${esc(project.base_branch)} · updated ${esc(date(project.jules_polled_at || project.updated_at))}</p><div class="agent-latest"><strong>${esc(item?.summary || (project.status === 'reserved' ? 'Reserved — not launched' : project.status === 'queued' ? 'Waiting for a launch slot' : 'No Jules activity yet'))}</strong>${item?.detail ? `<p>${esc(item.detail.slice(0, 400))}</p>` : ''}</div>${project.activity_error ? `<p class="agent-error">Activity feed: ${esc(project.activity_error)}</p>` : ''}<div class="agent-links"><a href="/projects/${esc(project.id)}">Inspect timeline and prompt →</a>${project.jules_session_url ? `<a href="${esc(project.jules_session_url)}" target="_blank" rel="noopener">Open in Jules ↗</a>` : ''}${project.pr_url ? `<a href="${esc(project.pr_url)}" target="_blank" rel="noopener">Pull request ↗</a>` : ''}</div></article>`;

}

export function activityPage({ projects, latest, defaults }) {
  const counts = {
    active: projects.filter(active).length,
    waiting: projects.filter(project => ['AWAITING_PLAN_APPROVAL', 'AWAITING_USER_FEEDBACK', 'PAUSED'].includes(project.jules_state)).length,
    finished: projects.filter(project => ['pr_validated', 'completed_no_pr', 'failed', 'pr_rejected'].includes(project.status)).length
  };
  const cards = projects.map(project => agentCard(project, latest.get(project.id))).join('');
  const refresh = projects.some(active);
  return layout('Jules agents', `<main><div class="page-heading"><div><div class="eyebrow">Live work</div><h1>Jules agents</h1><p class="lead">Each task appears here. Session states and activities are checked every 30 seconds${refresh ? '; this page refreshes every 20 seconds' : ''}.</p></div><div class="settings-actions"><a class="button ghost" href="/activity/settings">Agent settings</a><a class="button ghost" href="/activity">Refresh view</a></div></div><div class="metrics agent-metrics"><div><span>Active or queued</span><strong>${counts.active}</strong></div><div><span>Concurrency limit</span><strong>${esc(defaults.concurrency)}</strong></div><div><span>Needs attention</span><strong>${counts.waiting}</strong></div><div><span>Finished</span><strong>${counts.finished}</strong></div></div>${cards ? `<div class="agent-grid">${cards}</div>` : '<div class="empty">No projects yet. Add topics on the Projects page.</div>'}</main>`, { configured: true, autoRefresh: refresh });
}

export function agentSettingsPage({ defaults, csrfToken, activeCount, queuedCount, message, error }) {
  const runtimeOptions = ['15–30', '30–60', '60–120'].map(value => `<option value="${value}" ${defaults.runtime === value ? 'selected' : ''}>${value} minutes</option>`).join('');
  const autonomousMode = `<fieldset class="autonomy-setting"><legend>Unattended research</legend><input type="hidden" name="autoReplyPresent" value="1"><label class="check-option" for="autoReply"><input id="autoReply" name="autoReply" type="checkbox" value="1" ${defaults.autoReply ? 'checked' : ''}><span>Automatically tell Jules to continue when it asks for routine feedback</span></label><p class="help">On by default. Research Facility replies using the standing instructions in your prompt, at most three times per session for scheduled or manual work. Continuous orchestration always handles routine pauses without this cap.</p></fieldset>`;
  return layout('Agent settings', `<main class="narrow"><a class="back" href="/activity">← Back to agents</a><div class="eyebrow">Jules agents</div><h1>Agent settings</h1><p class="lead">Set how many tasks can work at once and how Jules handles routine pauses.</p>${notice(error, 'action', 'alert')}${notice(message, 'success')}<div class="metrics"><div><span>Working now</span><strong>${activeCount}</strong></div><div><span>Queued</span><strong>${queuedCount}</strong></div><div><span>Current limit</span><strong>${esc(defaults.concurrency)}</strong></div></div><form method="post" action="/activity/settings" class="form-card">${csrf(csrfToken)}<div class="field-grid"><div><label for="concurrency">Concurrency limit</label><input id="concurrency" name="concurrency" type="number" min="1" max="60" step="1" value="${esc(defaults.concurrency)}" required><p class="help">Maximum Jules tasks launched at the same time. Raising this starts waiting tasks; lowering it lets current tasks finish.</p></div><div><label for="runtime">Preferred runtime</label><select id="runtime" name="runtime">${runtimeOptions}</select><p class="help">Used only when the active prompt contains {{runtime}}.</p></div><div><label for="developmentSeeds">Development seeds</label><input id="developmentSeeds" name="developmentSeeds" type="number" min="1" max="100" step="1" value="${esc(defaults.developmentSeeds)}" required><p class="help">Used only when the active prompt contains {{development_seeds}}.</p></div><div><label for="finalSeeds">Final seeds</label><input id="finalSeeds" name="finalSeeds" type="number" min="1" max="100" step="1" value="${esc(defaults.finalSeeds)}" required><p class="help">Used only when the active prompt contains {{final_seeds}}.</p></div></div>${autonomousMode}<div class="form-actions"><button class="primary">Save agent settings</button><a href="/prompt">Edit research prompt</a></div></form><p class="help">Settings are saved locally and restored after restart. Runtime and seed changes affect new tasks only when the selected prompt uses those placeholders.</p></main>`, { configured: true });
}

export { orchestratorPage } from './orchestrator-ui.mjs';

function timelineItem(item) {
  return `<li class="timeline-item"><div class="timeline-head"><span class="status">${esc(label(item.kind))}</span><time>${esc(date(item.created_at))}</time></div><strong>${esc(item.summary)}</strong>${item.detail ? `<pre>${esc(item.detail)}</pre>` : ''}<small>${esc(item.originator)}</small></li>`;
}

export function projectPage({ project, activities, autoReplies = [], csrfToken, message, error }) {
  const timeline = activities.map(timelineItem).join('');
  const waitingForPlan = project.status === 'running' && project.jules_state === 'AWAITING_PLAN_APPROVAL';
  const waitingForReply = project.status === 'running' && ['AWAITING_USER_FEEDBACK', 'PAUSED'].includes(project.jules_state);
  const latestPlan = activities.find(item => item.kind === 'plan' && item.summary === 'Plan generated');
  const responseForPlan = autoReplies.find(item => item.activity_name === latestPlan?.name);
  const planPending = waitingForPlan && ['sending', 'sent', 'manual'].includes(responseForPlan?.status);
  const latestAgentMessage = activities.find(item => item.kind === 'message' && item.originator === 'agent');
  const responseForQuestion = autoReplies.find(item => item.activity_name === latestAgentMessage?.name);
  const replyPending = waitingForReply && ['sending', 'sent', 'manual'].includes(responseForQuestion?.status);
  const autoReplyNotice = responseForQuestion?.status === 'uncertain' ? `<div class="notice" role="alert">An automatic reply may not have reached Jules: ${esc(responseForQuestion.error)}. Inspect the session before replying again.</div>` : responseForPlan?.status === 'uncertain' ? `<div class="notice" role="alert">Automatic plan approval may not have reached Jules: ${esc(responseForPlan.error)}. Inspect the session before approving again.</div>` : responseForQuestion?.status === 'sent' && waitingForReply ? '<div class="notice success" role="status">Research Facility answered Jules using the autonomous research policy. Waiting for Jules to continue.</div>' : responseForPlan?.status === 'sent' && waitingForPlan ? '<div class="notice success" role="status">Research Facility approved the plan. Waiting for Jules to continue.</div>' : '';
  const planAction = waitingForPlan && !planPending ? `<section class="panel agent-response"><h2>Jules needs plan approval</h2><p>Review the generated plan in the timeline or open Jules before approving it.</p><form method="post" action="/projects/${esc(project.id)}/approve-plan">${csrf(csrfToken)}<button class="primary">Approve plan and continue</button></form></section>` : '';
  const replyAction = waitingForReply && !replyPending ? `<section class="panel agent-response"><h2>${project.jules_state === 'PAUSED' ? 'Jules is paused' : 'Jules needs your answer'}</h2>${latestAgentMessage ? `<p class="agent-question">${esc(latestAgentMessage.detail || latestAgentMessage.summary)}</p>` : '<p>Read the latest Jules message in the timeline or open the session to see what it needs.</p>'}<form method="post" action="/projects/${esc(project.id)}/reply">${csrf(csrfToken)}<label for="reply">Your reply to Jules</label><textarea id="reply" name="reply" rows="5" maxlength="10000" required placeholder="Answer the question or give Jules the missing information"></textarea><div class="form-actions"><button class="primary">Send reply to Jules</button></div></form></section>` : '';
  const stopAction = ['queued', 'running'].includes(project.status) ? `<form method="post" action="/projects/${esc(project.id)}/stop" class="form-actions">${csrf(csrfToken)}<button class="ghost" data-confirm="Stop this Jules task and release its repository slot?">Stop task</button></form>` : '';
  return layout(project.folder, `<main class="narrow"><a class="back" href="/activity">← All agents</a><div class="eyebrow">${esc(project.folder)}/</div><h1>${esc(project.topic)}</h1><div class="agent-detail-summary"><span class="status ${statusClass(project)}">${esc(project.jules_state ? label(project.jules_state) : label(project.status))}</span><span>${esc(project.repository_full_name)} · ${esc(project.base_branch)}</span></div>${notice(error, 'action', 'alert')}${notice(message, 'success')}${autoReplyNotice}${notice(project.error, 'action', 'alert')}${notice(project.activity_error ? `Activity feed: ${project.activity_error}` : '')}<div class="agent-links">${project.jules_session_url ? `<a href="${esc(project.jules_session_url)}" target="_blank" rel="noopener">Open in Jules ↗</a>` : ''}${project.pr_url ? `<a href="${esc(project.pr_url)}" target="_blank" rel="noopener">Pull request ↗</a>` : ''}<a href="/projects/${esc(project.id)}">Refresh view</a></div>${stopAction}${planAction}${replyAction}<section class="panel"><h2>Activity timeline</h2>${timeline ? `<ol class="timeline">${timeline}</ol>` : '<p class="help">No activities from Jules yet. The next poll will check again.</p>'}</section><details class="panel prompt-snapshot"><summary>Exact prompt sent to Jules</summary>${project.prompt_text ? `<pre>${esc(project.prompt_text)}</pre>` : `<p class="help">${project.jules_session_name ? 'This task launched before prompt snapshots were added.' : 'This task has not launched yet.'}</p>`}</details></main>`, { configured: true, autoRefresh: active(project) && (!waitingForReply || replyPending) });
}
